# Generated by Django 5.0 on 2023-12-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('complaint_time', models.DateTimeField(auto_now_add=True)),
                ('predicted_class', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
