# Generated by Django 5.0 on 2023-12-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('audio_file', models.FileField(null=True, upload_to='audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('converted_text', models.CharField(default='None', max_length=100, null=True)),
            ],
        ),
    ]
